name:                academic-soup
version:             0.1.1.0
github:              "Surobaki/academic-soup"
license:             BSD3
author:              "Olivia Hartley Weston"
maintainer:          "o.weston@pm.me"
copyright:           "2022 Olivia Hartley Weston"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            My personal website built using Slick.
category:            Slick-Site

description: Quite static multi-page website built on top of the Slick static site generator and deployed on Firebase.

executables:
  build-site:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base >= 4.7 && < 5
    - shake
    - slick
    - text
    - containers
    - unordered-containers
    - lens
    - aeson
    - lens-aeson
    - time
